  language: python
  python:
    - "3.6"
  before_script:
    - pip install -r test_requirements.txt --use-mirror
  script:
    - python -m unittest discover
    - coverage run test.py
    - coverage report 
  after_success:
    - coveralls
